version: 2
updates:
  - package-ecosystem: pip
    directory: "/{{cookiecutter.project_name}}"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "boto3"
        update-types: [ "version-update:semver-patch" ]