version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_{{cookiecutter.__project_slug}}
    ports:
      - "8000:8080"
    volumes:
      - ./nginx_compose:/etc/nginx/conf.d
      - ./data/static:/static
      - ./data/media:/media

    depends_on:
      web:
        condition: service_healthy
  db:
    image: postgres:13
    container_name: postgres_{{cookiecutter.__project_slug}}
    environment:
      - POSTGRES_DB={{cookiecutter.__project_slug}}_db #todo
      - POSTGRES_USER={{cookiecutter.__project_slug}}_user
      - POSTGRES_PASSWORD={{cookiecutter.__project_slug}}_pass
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U {{cookiecutter.__project_slug}}_user -d {{cookiecutter.__project_slug}}_db -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: ./ecs/Dockerfile

    environment:
      - DJANGO_ALLOWED_HOSTS=web,localhost,127.0.0.1
      - DJANGO_CONFIGURATION=Development
      - DJANGO_MEDIA_ROOT=/media/
      - DJANGO_SETTINGS_MODULE={{cookiecutter.__project_slug}}.settings
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - DATABASE_URL=postgresql://{{cookiecutter.__project_slug}}_user:{{cookiecutter.__project_slug}}_pass@db/{{cookiecutter.__project_slug}}_db
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py createsuperuser --username admin --email admin@admin.com --noinput && cat <<-000 | python manage.py shell
        from django.contrib.auth import get_user_model
        admin = get_user_model().objects.get(username='admin')
        admin.set_password('admin')
        admin.save()
        print('Superuser password updated successfully.')
        000
        python manage.py collectstatic --noinput
        cp /srv/app/static/* -r /static/
        gunicorn {{cookiecutter.__project_slug}}.wsgi --timeout 180 --bind 0.0.0.0

    volumes:
      - ./data/static:/static
      - ./data/media:/media
       - .:/srv/app # Mount the local folder directly, so no need for extra build

    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl http://web:8000/health_check || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5