[tool.poetry]
name = "{{cookiecutter.project_name|replace('_','-')}}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">3.10,<3.11"
Django = "^4.2"
django-configurations = "^2.4"
dj-database-url = "^2.0.0"
djangorestframework = "^3.14.0"
django-filter = "^23.1"
django-extensions = "^3.2.1"
django-import-export = "^3.2.0"
django-storages = "^1.13.2"
Pillow = "^9.5.0"
django-cors-headers = "^4.0.0"
django-querycount = "^0.8.3"
gunicorn = "^20.1.0"
djangorestframework-simplejwt = "^5.2.1"
psycopg = "^3.1.8"
drf-nested-routers = "^0.93.4"
drf-spectacular = "^0.26.2"
boto3 = ">=1.26.24"
#whitenoise = ">=6.2.0" #uncomment in heroku

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
