[tool.poetry]
name = "{{cookiecutter.project_name|replace('_','-')}}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">{{cookiecutter.python_version}},<3.12"
Django = "^4.2"
django-configurations = "^2.5"
dj-database-url = "^2.1.0"
djangorestframework = "^3.14.0"
django-filter = "^23.5"
django-extensions = "^3.2.3"
django-import-export = "^3.3.4"
django-storages = "^1.14.2"
Pillow = "^10.1.0"
django-cors-headers = "^4.3.1"
django-querycount = "^0.8.3"
gunicorn = "^21.2.0"
djangorestframework-simplejwt = "^5.3.1"
psycopg = "^3.1.15"
drf-nested-routers = "^0.93.4"
drf-spectacular = "^0.26.5"
boto3 = ">=1.28.60"

{ % - if cookiecutter.heroku_app_name | length - %}
whitenoise = ">=6.2.0" #for heroku serving static files for admin
{ % - endif - %}


[tool.poetry.dev-dependencies]
pytest = "^7.4.2"
ruff = "^0.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88

# To never enforce `E501` (line length violations) uncomment the next line
# ignore = ["E501"]
