[tool.poetry]
name = "{{cookiecutter.project_name|replace('_','-')}}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">={{cookiecutter.python_version}},<{{cookiecutter.__max_python_version}}"
Django = "^5.0.6"
django-configurations = "^2.5.1"
dj-database-url = "^2.2.0"
djangorestframework = "^3.15.2"
django-filter = "^24.2"
django-extensions = "^3.2.3"
django-import-export = "^4.0.9"
django-storages = "^1.14.3"
Pillow = "^10.3.0"
django-cors-headers = "^4.4.0"
django-querycount = "^0.8.3"
gunicorn = "^22.0.0"
djangorestframework-simplejwt = "^5.3.1"
psycopg = "^3.1.19"
drf-nested-routers = "^0.94.1"
drf-spectacular = "^0.27.2"
boto3 = ">=1.34.133"
pytz = "^2024.1"

{%  if cookiecutter.heroku_app_name | length %}
whitenoise = ">=6.6.0" #for heroku serving static files for admin
{% else %}

{%  endif %}


[tool.poetry.dev-dependencies]

pytest = "^8.2.2"
ruff = "^0.4.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88

# To never enforce `E501` (line length violations) uncomment the next line
# ignore = ["E501"]
